# Generated by Django 5.1.6 on 2025-04-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('penname', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('snapchat', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('edu_details', models.JSONField()),
            ],
        ),
    ]
