# Generated by Django 5.1.6 on 2025-04-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='id',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='username',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
