# Generated by Django 5.1.6 on 2025-04-21 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Current status of the friend request', max_length=10),
        ),
        migrations.AddIndex(
            model_name='friend',
            index=models.Index(fields=['user1', 'user2'], name='friendship_users_idx'),
        ),
        migrations.AddIndex(
            model_name='friend',
            index=models.Index(fields=['created_at'], name='friendship_date_idx'),
        ),
        migrations.AddIndex(
            model_name='friendrequest',
            index=models.Index(fields=['sender', 'status'], name='fr_sender_status_idx'),
        ),
        migrations.AddIndex(
            model_name='friendrequest',
            index=models.Index(fields=['receiver', 'status'], name='fr_receiver_status_idx'),
        ),
    ]
